version: '2.1'
networks:
  app_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
services:
  gate:
    build:
      context: ./gate
#    command: ["--debug"]
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  test:
    build:
      context: ./test
#    command: ["--debug"]
    networks:
      app_net:
        ipv4_address: 172.16.238.12